[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.14"
rust_socketio = "0.6.0"
anyhow = {workspace = true}
serde = { workspace = true }
serde_json = { workspace = true }