[package]
name = "netcode"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
chrono.workspace = true
macroquad = "0.4.14"
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = {workspace = true}
rust_socketio = "0.6.0"
