[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.4"
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
socketioxide = "0.16.2"